name: Deploy PWA to GitHub Pages

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CI: false

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'
      actions: 'write'
      checks: 'write'
      deployments: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'www/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
